### ISSUE TITLE
[Feat] 로그인 및 회원가입 화면 수정

### ISSUE THREAD

**Issue by compuTasha** [GDSC-KNU/TIL-Frontend#5]
## 💡 Issue

로그인 및 회원가입 화면 수정하기

<img width="2047" alt="image" src="https://user-images.githubusercontent.com/51108729/171008795-1a7ce444-ce05-4869-addb-70efad518e29.png">

## 📝  todo
- [x] 전체적인 레이아웃 수정하기
- [x] 앱 아이콘 추가하기
- [x] rounded button으로 변경하기
- [x] password toggle 추가하기
