### ISSUE TITLE
[Feat] 메인 화면 (캘린더, TIL 목록) 디자인 수정

### ISSUE THREAD

**Issue by compuTasha** [GDSC-KNU/TIL-Frontend#7]
## 💡 Issue

메인 화면 수정하기

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/51108729/171430783-39a4eceb-a35e-496d-9f0f-f546dd6db1b8.png">

## 📝  todo
- [ ] 전체적인 레이아웃 수정하기
- [ ] 검색창 수정하기
- [ ] 캘린더 하단 RecyclerView 수정하기
- [ ] 캘린더 오늘 날짜 선택시 날짜가 안 보이는 오류 수정하기
- [ ] 플로팅 버튼 수정하기
